-- 코드를 입력하세요
SELECT book.BOOK_ID, author.AUTHOR_NAME, date_FORMAT(book.PUBLISHED_DATE, '%Y-%m-%d')
from BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID

WHERE BOOK.CATEGORY = '경제'

ORDER BY BOOK.PUBLISHED_DATE;